
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fruit_suppliers
    container_name: fruit_supplier
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: fruit_suppliers
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: fruit_supplier-mysqls
    restart: unless-stopped
    tty: true
    ports:
      - "13307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: chinhhn
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Nginx Service
  web:
    image: 'nginx:alpine'
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
